In [179]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from ta import *

data = pd.read_csv('AAPL.csv')
data = data.drop('Close',1)
data = data.rename(columns={'Adj Close':'Close'})
data.tail()

Date        Open        High         Low       Close      Volume
9820  2019-11-21  263.690002  264.010010  261.179993  262.010010  30348800.0
9821  2019-11-22  262.589996  263.179993  260.839996  261.779999  16331300.0
9822  2019-11-25  262.709991  266.440002  262.519989  266.369995  21005100.0
9823  2019-11-26  266.940002  267.160004  262.500000  264.290009  26301900.0
9824  2019-11-27  265.579987  267.980011  265.309998  267.839996  16308900.0

In [180]:
X = data.iloc[:,1:]
X = X.drop('Open',1)
X.head()

High       Low     Close       Volume
0  0.515625  0.513393  0.407747  117258400.0
1  0.488839  0.486607  0.386473   43971200.0
2  0.453125  0.450893  0.358108   26432000.0
3  0.464286  0.462054  0.366972   21610400.0
4  0.477679  0.475446  0.377609   18362400.0

In [181]:
#Calculating the Technical Indicators
X['SMA'] = X['Close'].rolling(window=10).mean()
X['EMA'] = X['Close'].ewm(span=20, adjust=False).mean()
X['STCK'] = momentum.stoch(X['High'], X['Low'], X['Close'], n=14, fillna=False)
X['STCD'] = momentum.stoch_signal(X['High'], X['Low'], X['Close'], n=14, d_n=3, fillna=False)
X['MACD'] = trend.macd(X['Close'], n_fast=12, n_slow=26, fillna=False)
X['RSI'] = momentum.rsi(X['Close'], n=10,fillna=False)
X['WR'] = momentum.wr(X['High'], X['Low'], X['Close'], lbp=14, fillna=False)
X['AD'] = volume.acc_dist_index(X['High'], X['Low'], X['Close'], X['Volume'], fillna=False)
X['CCI'] = trend.cci(X['High'], X['Low'], X['Close'], n=20, c=0.015, fillna=False)
X = X.iloc[25:,:]
X = X.dropna()
X.head()


High       Low     Close     Volume       SMA       EMA        STCK  \
25  0.571429  0.569196  0.452067  7520800.0  0.443558  0.445913 -109.650684   
26  0.584821  0.580357  0.460931  3976000.0  0.445862  0.447344  -98.619909   
27  0.591518  0.587054  0.466250  8887200.0  0.449585  0.449144 -114.207811   
28  0.589286  0.584821  0.464477  2805600.0  0.450826  0.450605 -147.455151   
29  0.578125  0.575893  0.457386  6160000.0  0.451713  0.451250 -161.267263   

          STCD      MACD        RSI          WR            AD        CCI  
25  -96.089731  0.001555  52.221357 -209.650684 -1.931980e+09 -20.630980  
26  -97.023912  0.002221  58.418856 -198.619909 -1.013225e+09   1.939718  
27 -107.492801  0.003094  62.030979 -214.207811 -7.066119e+08  14.991341  
28 -120.094290  0.003611  59.910670 -247.455151 -6.439378e+08   8.302432  
29 -140.976741  0.003458  51.333562 -261.267263 -8.143275e+08 -10.991937

In [182]:
# new_X = ['Close',SMA','EMA','STCK','STCD','MACD','RSI','WR','AD','CCI']
X.size


127140

In [183]:
k=0
new_X = []
j = []
X_list = [X.values.tolist()]
len(X_list[0])

#print(X_list[0])

for i in X_list[0]:
    l = []
#     print(i)
#     j=i
#     print(j)
    if k==0:
        k=1
        j=i
        continue
      
    #Close
    l.append(i[2])
    
    #SMA
    if i[2]>=i[4]:
        l.append(1)
    else:
        l.append(-1)
#     print(i[2])
    
    #EMA
    if i[2]>=i[5]:
        l.append(1)
    else:
        l.append(-1)
#     print((i[2]>=i[5]))

    #Stck
    if i[6] >= j[6]:
        l.append(1)
    else:
        l.append(-1)
#     print(l)
           
    #STCD
    if i[7] >= j[7]:
        l.append(1)
    else:
        l.append(-1)
#     print(l)
    
    #MACD
    if i[8] >= j[8]:
        l.append(1)
    else:
        l.append(-1)
#     print(l)
        
    #RSI
    if i[9]<30:
        l.append(1)
    elif i[9]>70:
        l.append(-1)
    else:
        if i[9]>=j[9]:
            l.append(1)
        else:
            l.append(-1)
#     print(l)
        
    #WR
    if i[10] >= j[10]:
        l.append(1)
    else:
        l.append(-1)
#     print(l)

    #AD
    if i[11] >= j[11]:
        l.append(1)
    else:
        l.append(-1)
        
    #CCI
    if i[12]<-200:
        l.append(1)
    elif i[12]>200:
        l.append(-1)
    else:
        if i[12]>=j[12]:
            l.append(1)
        else:
            l.append(-1)
#     print(i[11])
#     print(j[11])
    

#     print(l)
    
        
    #Append to new_X
    new_X.append(l)
    j=i

In [184]:
new_X = pd.DataFrame(new_X, columns =['Close','SMA','EMA','STCK','STCD','MACD','RSI','WR','AD','CCI'], dtype = float)
new_X.tail()

Close  SMA  EMA  STCK  STCD  MACD  RSI   WR   AD  CCI
9774  262.010010 -1.0  1.0  -1.0  -1.0  -1.0 -1.0 -1.0 -1.0 -1.0
9775  261.779999 -1.0  1.0  -1.0  -1.0  -1.0 -1.0 -1.0 -1.0 -1.0
9776  266.369995  1.0  1.0   1.0   1.0  -1.0  1.0  1.0  1.0  1.0
9777  264.290009 -1.0  1.0  -1.0   1.0  -1.0 -1.0 -1.0 -1.0 -1.0
9778  267.839996  1.0  1.0   1.0   1.0  -1.0  1.0  1.0 -1.0  1.0

In [185]:
y = np.where (new_X['Close'].shift(-1) > new_X['Close'],1,-1)
y

array([ 1, -1, -1, ..., -1,  1, -1])

In [186]:
y.size

9779

In [187]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(new_X.iloc[:,1:], y, test_size = 0.25, random_state = 42)

In [188]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators= 1500, random_state = 32)
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1500, n_jobs=None,
            oob_score=False, random_state=32, verbose=0, warm_start=False)

In [189]:
y_pred = rf.predict(X_test)

In [190]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[692 516]
 [688 549]]
              precision    recall  f1-score   support

          -1       0.50      0.57      0.53      1208
           1       0.52      0.44      0.48      1237

   micro avg       0.51      0.51      0.51      2445
   macro avg       0.51      0.51      0.51      2445
weighted avg       0.51      0.51      0.51      2445

0.5075664621676892


In [191]:
x_pred = np.array([1,1,1,1,-1,1,1,-1,1])
rf.predict(x_pred.reshape(1,-1))

array([1])